### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [MihutBalasanu/VendingMachine#2]
https://github.com/MihutBalasanu/VendingMachine/blob/a81ba569d48e6805a15cc6bc71f6f6d133b31b9f/20181021_VendingMachine/src/VendingMachine.java#L204

E bun cum e facut, doar ca daca mai adaugi ceva in fisier atunci trebuie sa modifici codul.
Ideal ar fi in fisier, inainte de produse sau monezi sa citesti cate urmeaza
De exemplu:
COFFEE
RON
5
--5 produse--
3
--3 monezi--

-- -- inseamna ca acolo sunt listare produsele / monezile

**Comment by MihutBalasanu** [comment]
Am inteles si am modificat.
